#Geese are cool!

spring:
    profile:
        active: run

#Feign
feign:
    client:
        config:
            openExchangeRates:
                errorDecoder: com.alpha.currencyExchange.rateProviders.openExchangeRates.OpenExchangeRatesErrorDecoder
            default:
                errorDecoder: com.alpha.currencyExchange.rateProviders.openExchangeRates.OpenExchangeRatesErrorDecoder
            giphy:
                errorDecoder: com.alpha.visualMedia.gif.giphy.GiphyErrorDecoder

#Application-specific configurations

OpenExchangeRates:
    URL: https://www.openexchangerates.org
    AppId: 57676e267330400596732bd46c5e85e6
    DefaultBaseCurrencyId: USD

Giphy:
    URL: https://api.giphy.com
    AppId: CkoTrxQ867g5eqoGj66cVj5kUjFFhjN0